services:
    sonata.admin.price:
        class: AppBundle\Admin\PriceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Контент", label: "Тарифы" }
        arguments:
            - ~
            - AppBundle\Entity\Price
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
    sonata.admin.sale:
        class: AppBundle\Admin\SaleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Контент", label: "Акции/Новости" }
        arguments:
            - ~
            - AppBundle\Entity\Sale
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
    sonata.admin.comment:
        class: AppBundle\Admin\CommentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Контент", label: "Отзывы" }
        arguments:
            - ~
            - AppBundle\Entity\Comment
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
    sonata.admin.email:
        class: AppBundle\Admin\EmailAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Админ", label: "Модераторы комментов" }
        arguments:
            - ~
            - AppBundle\Entity\Email
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]