<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceRepository extends EntityRepository
{
    public function findLastPrice()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p.price, p.vip, p.hygiene, p.day, p.evening, p.special
                FROM AppBundle:Price p
                ORDER BY p.id DESC'
            )
            ->setMaxResults(1)
            ->getResult();
    }
}
