<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleRepository extends EntityRepository
{
    public function findTopSales($max)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p.salestext, p.cat
                FROM AppBundle:Sale p
                WHERE p.status = 1
                ORDER BY p.datecr DESC'
            )
            ->setMaxResults($max)
            ->getResult();
    }
}
